# Generated by Django 3.1.6 on 2024-03-10 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('avatar', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryMedecine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100)),
                ('poste', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=54)),
                ('description', models.CharField(max_length=500)),
                ('employee_id', models.CharField(max_length=50)),
                ('avatar', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Medecine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medecine_name', models.CharField(max_length=70, unique=True)),
                ('price', models.CharField(max_length=6)),
                ('quantity', models.FloatField()),
                ('expire_date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('delevery_date', models.DateField()),
                ('avatar', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('entreprise', models.CharField(max_length=50)),
                ('avatar', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_Name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.CharField(max_length=50)),
                ('Admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med.administrateur')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med.medecine')),
            ],
        ),
        migrations.CreateModel(
            name='Buys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med.medecine')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med.provider')),
            ],
        ),
    ]
