# Generated by Django 3.1.6 on 2024-03-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0002_medecine_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='buys',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medecine',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
