# Generated by Django 3.1.6 on 2024-03-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0003_auto_20240314_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='buys',
            name='avatar',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
    ]
