# Generated by Django 3.1.6 on 2024-03-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0004_buys_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buys',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
